### ISSUE TITLE
HTTP ERROR 500 on callback

### ISSUE THREAD

**Issue by KelsoField** [s-patompong/hmrc-api-php#13]
After successful setup and config, I am receiving HTTP ERROR 500 on the callback after authorise post from HMRC test server.

Flow is as follows:
examples/index loaded with config data.
create access token submit
Authority page on HMRC loads, continue clicked.
Successful test user sign in
Authority granted
HMRC redirect_uri fires

This is installed onto a LAMP server and all paths have been updated to correct values so it is not that, it attempts to load the correct script, just halts on 500.
The same error happens if initial create access token results in an error and oauth2/destroy-session.php has to be fired in order to continue.

I assume this is related to the session, but cannot figure out what is causing this.

Help appreciated

Keith

**Comment by s-patompong** [comment]
Hi Keith, 

I'll need to ask some simple questions to clarify the scenario, please see below.

1. Do you have error trace or something that I can read and see what's wrong?
2. So basically the error occurred when HMRC redirect back to localhost?

**Comment by KelsoField** [comment]
Unfortunately, no trace and yes this happens after successful login of test account at HMRC and redirect fired.

As I am just testing, I have made no changes to the structure. This will be done only once this method is verified as working so apart from not being root of a directory, this is the full callback string.
https://daso-id.com/vat/examples/oauth2/callback.php?code=c6f6520a2fcb4d068598b310146a620c&state=d4d3b52ed03883aa8ef7d3dbbeb8df89

**Comment by s-patompong** [comment]
Do you use sandbox or live environment? I guess you're using live since the url isn't localhost (HMRC only allows localhost when testing sandbox).

Maybe there is a problem with session being unable to initialise. But without trace it's really hard to debug :/

**Comment by DarkSide666** [comment]
@s-patompong you're wrong on localhost. HMRC allows any domain/URI as callback. You just have to register that callback URI in HMRC account/page.

Also I noticed that this callback URI is HTTPS. Maybe some issue related to SSL?

**Comment by KelsoField** [comment]
I am using the sandbox and testing via a we server not a local box.
The callbackUri within create-access-token is seemingly ignored by hmrc.
I had to add the callback to the sandbox application setup in order for
it to work.
After doing that I did not get a return_uri error from hmrc and was able to
proceed to auth.
First attempt failed so I married the return uri with the callbackUri and
still failed.

When you say trace, what do you recommend, as I generally code live and
have never relied on anything but a standard dev console to get me out of
any issue.

Thanks for your time.

**Comment by DarkSide666** [comment]
callbackURI is not ignored. You just have to add it in HMRC account for it to work.

Trace - xDebug probably.

Anyway issue is in you server or callback.php file and not releated to HMRC.
Try debugging callback.php file step by step by adding var_dump(bla bla) line after line :)

Possible issues:
* something bad with composer (vendor folder)
* bad session support (session_start)
* header() at the end redirects to bad uri

**Comment by KelsoField** [comment]
They are the same, married them up as part of my testing.
I had to do this anyways as localhost is not vaible in production.

**Comment by DarkSide666** [comment]
just add var_dump() line by line in callback.php and find the exact line which fails.

**Comment by s-patompong** [comment]
> @s-patompong you're wrong on localhost. HMRC allows any domain/URI as callback. You just have to register that callback URI in HMRC account/page.
> 
> Also I noticed that this callback URI is HTTPS. Maybe some issue related to SSL?

Yep, my bad. I use http when test so it allows me to use only localhost. I just tested it again with https and it allows me to use any domain. Thanks for the correction 👍

**Comment by KelsoField** [comment]
I am getting there, but it seems we have more issues, albiet I think this is due to HMRC...
When trying to submit a return, it 500's but the error in the log points to an invalid callback.
INVALID_MONETARY_AMOUNT
After a bit of investigating (no documentation of course) It "appears" decimals above 0 are not allowed. Crazy!
SO, changing the values to none decimal should fix this?
Nope, it still errors as follows.

[18-Mar-2019 15:52:36 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://test-api.service.hmrc.gov.uk/organisations/vat/308048082/returns` resulted in a `400 Bad Request` response:
{"code":"INVALID_REQUEST","message":"Invalid request","errors":[{"code":"INVALID_MONETARY_AMOUNT","message":"amount shou (truncated...)
 in /home/vat/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/vat/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/vat/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/vat/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /home/vat/vendor/guzzlehttp/promises/src/TaskQueue.php( in /home/vat/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

Anyone else getting this issue?

**Comment by DarkSide666** [comment]
Yes this one was annoying. HMRC server really sucks :)

Be very very precise when you submit your data:
1. some fields should be without decimals (even 123.00 will be considered as decimals). Should be just 123
2. some fields allow 2 decimal symbols. BUT ONLY 2 and no more!!! If you pass something like 123.456 it will fail. Or if you use float number like 123.45 and use some version of PHP 7.1, then json_encode will convert it to 123.4500000000001 and again HMRC service will fail. See this fix of mine https://github.com/s-patompong/hmrc-api-php/commit/182295d19b60ef58beb34e37a43082f0c17daf02
3. some fields allow only positive values! Even VAT return should ALWAYS be positive so use ABS(net_vat_due) there.

There are a lot of angry messages in HMRC github page about this :)

**Comment by DarkSide666** [comment]
Also you have to use better Exception / Error handling otherwise you will not be able to see full error messages.

For example, something like this:
```
        try {
            $response = $request->fire();
        } catch (\GuzzleHttp\Exception\GuzzleException $e) {
            if ($e->hasResponse()) {

                /* @var GuzzleHttp\Psr7\Response */
                $resp = $e->getResponse();

                $body = $resp->getBody();
                $size = $body->getSize();
                if ($size > 0) {
                    $resp_json = json_decode($body->read($size), true);
                    $body->rewind();

                    throw new \atk4\core\Exception(array_merge(
                            [
                                $resp->getStatusCode().': '.$resp->getReasonPhrase(), // error message
                                'values_sent' => $postBody->toArray(), // values you sent
                            ],
                            $resp_json // full response
                        ), $e->getCode(), $e);
                }
            }

            throw new \atk4\core\Exception([
                    $e->getMessage(),
                ], $e->getCode(), $e);
        }

        $data = $response->getArray();
```

**Comment by KelsoField** [comment]
Managed to sort, it is very frustrating with the lack of concise documentation form HMRC. Thanks all
