### ISSUE TITLE
Don't rely on SESSION

### ISSUE THREAD

**Issue by DarkSide666** [s-patompong/hmrc-api-php#7]
One bad thing about this solution is that it relies on SESSION.

In my case, for example, I store tokens in database and don't actually need setting SESSION variables at all.
It probably would be good to have some kind of `Storage` or `Data model` class which takes care of that and can be easily extended to replace session storing to something else (like saving/loading to/from database).

**Comment by s-patompong** [comment]
I had a problem when I tried to think where I should put the access token. I want the user of this library to be able to use the request class without worrying about the access token (or passing it to the request), so I go with session (and make it a singleton class).

Do you have suggestion how some request should be called if we change the way we store the access token for example?

I'm down if it can improve the maintainability and/or flexibility going forward.

**Comment by s-patompong** [comment]
Any thought on this @DarkSide666?

If we do change the implementation, I might need to change the version to 2.X, I've already have the code goes live here.

**Comment by DarkSide666** [comment]
Well, I think it's OK as it is. It works for demo, but in real app we can store that token anywhere else (database for example).
Another option would be to use some separate storage engine class, but that will add more dependencies and that's not always welcome.

**Comment by s-patompong** [comment]
I can see what you mean. In my app right now I store access token in DB. Then I use the middleware to grab it and set it using AccessToken class every time customer calls VAT endpoints.

**Comment by DarkSide666** [comment]
yeah. I am doing the same :)

**Comment by s-patompong** [comment]
Issue close for now, I can re-implement it later with new version if necessary.
