### ISSUE TITLE
Are you interested in PRs ?

### ISSUE THREAD

**Issue by DarkSide666** [s-patompong/hmrc-api-php#8]
Are you interested in pull requests?

I have added these services https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/api-platform-test-user/1.0#_create-a-test-user-which-is-an-agent_post_accordion because they are required to create test user. Creating test user in HMRC homepage is full with bugs and only creating them by API works correct.

I can share the code if you include it in your repo. Otherwise I will have to make my fork and add the things I need there and separate from you.

**Comment by s-patompong** [comment]
PR is more than welcome, personally I start developing VAT endpoints because that's what we want to use initially in my company.

It would be nice if we can add another endpoints as well so other people that want other stuff (like self assessment endpoints) can use this library.

**Comment by DarkSide666** [comment]
I only needed VAT endpoints myself, but create test user endpoints are required too because if you create test user by using HMRC homepage then it will not work correct. Only correct way how to create test user is by using API calls.
I will prepare PR in next few days.

**Comment by s-patompong** [comment]
Or, if you want it easy way, I can provide you the CURL call from Postman as well. I did use Postman to create test user so I didn't have to write request for it in this library.

But yeah, PR would be better so other people can use it as well.

**Comment by DarkSide666** [comment]
exactly.
also I needed ability to create multiple test users (by using my client app while they do testing) so Postman wasn't good option.
