### ISSUE TITLE
class loading issue

### ISSUE THREAD

**Issue by KelsoField** [s-patompong/hmrc-api-php#9]
I am looking into this class and cannot get the classes to load.

I have installed manually onto my test server (LAMP) and after altering the config, I navigate to examples/ dir and I get the error
Fatal error: Class 'HMRC\Oauth2\AccessToken' not found in /xxxx/xxx

This is using namespacing, but for the life of me I cannot get it to fire.
Any thoughts appreciated.

Many Thanks

**Comment by DarkSide666** [comment]
Use Composer to install it and then just include `./vendor/autoload.php` in your script.

**Comment by KelsoField** [comment]
composer is not an option at this time as it is a remote server.
Is there no manual way to resolve this?
Does anyone have a copy of the contents of this file so I can replicate?

Thanks

**Comment by s-patompong** [comment]
You can try install dependencies on your computer and upload the vendor/ folder to remote server. But that will add a lot of work since you'll need to re-upload the vendor folder every time we have an update.
